<a href="https://colab.research.google.com/github/abd-syah33/S3_Pengenalan-Pola/blob/Praktikum-1-%26-2/Praktikum_Pengenalan_Pola_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Review – Representasi Data dalam Python

In [1]:
# vektor python numpy with range value
import numpy as np
print("vektor default python\n")
a = np.arange(1,20,1)
b = np.arange(1,20,2)

import numpy as np
print (" \n vektor via numpy \n")

# vektor via numpy
c = np.array ([1,2,3,4,5])
d = np.array ([1.5, 2.5, 5, 6, 7])

print(a)
print(b)
print(a.ndim)
print(a.shape)


vektor default python

 
 vektor via numpy 

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
1
(19,)


In [2]:
# mengubah dari 1D menjadi matrik 2D
a = np.arange(1,21,1)
c = a.reshape((4,5))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [3]:
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]
list4 = ["abc", 34, True, 40, "male"]

print(list1);



['apple', 'banana', 'cherry']


In [4]:
#data frame
import pandas as pd
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
                        columns=['a', 'b', 'c'])

print(df)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9


Import dan Export data serta manipulasinya

In [7]:
# Membaca data dari file dengan format CSV
import pandas as pd
data = pd.read_csv("Data.csv", sep=";")
print(data)

FileNotFoundError: [Errno 2] No such file or directory: 'Data.csv'

In [8]:
# Membaca data dari file dengan format text (delimeter)
print("\n read text data with tab delimiter")
with open ('Data.txt') as data:
    print(data.read())


 read text data with tab delimiter


FileNotFoundError: [Errno 2] No such file or directory: 'Data.txt'

In [9]:
# Membaca data dari URL
import pandas as pd
f = pd.read_csv('http://www.exploredata.net/ftp/Spellman.csv')
print(f)

         time     40    50     60    70    80    90   100   110   120  ...  \
0     YAL001C -0.070 -0.23 -0.100  0.03 -0.04 -0.12 -0.28 -0.44 -0.09  ...   
1     YAL014C  0.215  0.09  0.025 -0.04 -0.04 -0.02 -0.51 -0.08  0.00  ...   
2     YAL016W  0.150  0.15  0.220  0.29 -0.10  0.15 -0.73  0.19 -0.15  ...   
3     YAL020C -0.350 -0.28 -0.215 -0.15  0.16 -0.12  0.26  0.00  0.13  ...   
4     YAL022C -0.415 -0.59 -0.580 -0.57 -0.09 -0.34  0.49  0.32  1.15  ...   
...       ...    ...   ...    ...   ...   ...   ...   ...   ...   ...  ...   
4376  YPR198W -0.060  0.08  0.210  0.34  0.65 -0.26  0.14 -0.33  0.53  ...   
4377  YPR199C  0.155  0.19  0.235  0.28 -0.26  0.21 -0.40  0.34 -0.80  ...   
4378  YPR201W -0.255 -0.36 -0.300 -0.24  1.30 -0.07  0.29 -0.20  0.25  ...   
4379  YPR203W  0.570  0.12 -0.070 -0.26 -0.44 -0.21 -1.08  0.39 -0.17  ...   
4380  YPR204W  0.405  0.17 -0.045 -0.26 -0.60 -0.09 -0.85  0.17 -0.05  ...   

       170   180   190   200   210   220   230   240   250    2